# Generated by Django 4.2.1 on 2023-07-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='email',
            new_name='email_profile',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='first_name',
            new_name='first_profile_name',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='last_name',
            new_name='last_profile_name',
        ),
    ]
