# Generated by Django 4.2.1 on 2023-07-08 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0004_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='group',
            field=models.ForeignKey(blank=True, default='Customers', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
