# Generated by Django 4.2.1 on 2023-07-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_address_user'),
        ('cart', '0009_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='contact_phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profile.customerprofile'),
        ),
    ]
