# Generated by Django 4.2.1 on 2023-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_cart_contact_phone_cart_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_comment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cart comment'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart_comment_in_order',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cart comment in order'),
        ),
    ]
